# Generated by Django 4.2.16 on 2024-09-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Shopname', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Emailid', models.CharField(blank=True, max_length=20, null=True)),
                ('Phonenumber', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
