# Generated by Django 4.2.16 on 2024-09-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0002_producttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='Productimages',
            field=models.FileField(blank=True, null=True, upload_to='productimages'),
        ),
    ]
